INSERT INTO ESPECIALIDADE VALUES (1,'Oncologia');
INSERT INTO ESPECIALIDADE VALUES (2,'Consulta Externa');
INSERT INTO ESPECIALIDADE VALUES (3,'Oftalmologia');
INSERT INTO ESPECIALIDADE VALUES (4,'Urgências');
INSERT INTO ESPECIALIDADE VALUES (5,'Pediatria');
INSERT INTO ESPECIALIDADE VALUES (6,'Cardiologia');
INSERT INTO ESPECIALIDADE VALUES (7,'Radiologia');
INSERT INTO ESPECIALIDADE VALUES (8,'Neurologia');