 CREATE TABLE "WORK"."TABLESPACES" 
   (	"ID_TABLESPACE" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE), 
	"ALLOCATED" NUMBER(*,0), 
	"FREE" NUMBER(*,0), 
	"USED" NUMBER(*,0), 
	"MAX_BYTES" VARCHAR2(20 BYTE), 
	 CONSTRAINT "TABLESPACES_PK" PRIMARY KEY ("ID_TABLESPACE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "WORK_TABLE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WORK_TABLE" ;
  
  
  
CREATE TABLE "WORK"."DATAFILES" 
   (	"ID_DATAFILE" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE), 
	"SIZED" NUMBER(*,0), 
	"STATUS" VARCHAR2(200 BYTE), 
	"ID_TABLE" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "DATAFILES_PK" PRIMARY KEY ("ID_DATAFILE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "WORK_TABLE"  ENABLE, 
	 CONSTRAINT "DATAFILES_FK1" FOREIGN KEY ("ID_TABLE")
	  REFERENCES "WORK"."TABLESPACES" ("ID_TABLESPACE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WORK_TABLE" ;

  
  
 
CREATE TABLE "WORK"."USERS" 
   (	"ID_USER" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(200 BYTE), 
	"EXP_DATE" DATE, 
	"TEMP_TABLESPACE" VARCHAR2(200 BYTE), 
	"CREATED" DATE, 
	"USER_TYPE" VARCHAR2(200 BYTE), 
	"ID_TABLESPACE" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "WORK_TABLE"  ENABLE, 
	 CONSTRAINT "USERS_FK1" FOREIGN KEY ("ID_TABLESPACE")
	  REFERENCES "WORK"."TABLESPACES" ("ID_TABLESPACE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WORK_TABLE" ;
  
  
  
  CREATE TABLE "WORK"."ROLES" 
   (	"ID_ROLE" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	 CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "WORK_TABLE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WORK_TABLE" ;
  
  
    CREATE TABLE "WORK"."USERS_ROLES" 
   (	"ID_UR" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_USER" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ROLES" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_ROLES_PK" PRIMARY KEY ("ID_UR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "WORK_TABLE"  ENABLE, 
	 CONSTRAINT "USERS_ROLES_FK1" FOREIGN KEY ("ID_ROLES")
	  REFERENCES "WORK"."ROLES" ("ID_ROLE") ENABLE, 
	 CONSTRAINT "USERS_ROLES_FK2" FOREIGN KEY ("ID_USER")
	  REFERENCES "WORK"."USERS" ("ID_USER") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WORK_TABLE" ;
